lock-version = "1.0"
created-by = "pip"

[[packages]]
name = "argcomplete"
version = "3.6.3"

[[packages.wheels]]
name = "argcomplete-3.6.3-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/74/f5/9373290775639cb67a2fce7f629a1c240dce9f12fe927bc32b2736e16dfc/argcomplete-3.6.3-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "f5007b3a600ccac5d25bbce33089211dfd49eab4a7718da3f10e3082525a92ce"

[[packages]]
name = "build"
version = "1.3.0"

[[packages.wheels]]
name = "build-1.3.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/cb/8c/2b30c12155ad8de0cf641d76a8b396a16d2c36bc6d50b621a62b7c4567c1/build-1.3.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "7145f0b5061ba90a1500d60bd1b13ca0a8a4cebdd0cc16ed8adf1c0e739f43b4"

[[packages]]
name = "cachetools"
version = "6.2.4"

[[packages.wheels]]
name = "cachetools-6.2.4-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/2c/fc/1d7b80d0eb7b714984ce40efc78859c022cd930e402f599d8ca9e39c78a4/cachetools-6.2.4-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "69a7a52634fed8b8bf6e24a050fb60bff1c9bd8f6d24572b99c32d4e71e62a51"

[[packages]]
name = "certifi"
version = "2025.11.12"

[[packages.wheels]]
name = "certifi-2025.11.12-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/70/7d/9bc192684cea499815ff478dfcdc13835ddf401365057044fb721ec6bddb/certifi-2025.11.12-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "97de8790030bbd5c2d96b7ec782fc2f7820ef8dba6db909ccf95449f2d062d4b"

[[packages]]
name = "cffi"
version = "2.0.0"

[[packages.wheels]]
name = "cffi-2.0.0-cp313-cp313-manylinux2014_aarch64.manylinux_2_17_aarch64.whl"
url = "https://files.pythonhosted.org/packages/a9/f5/a2c23eb03b61a0b8747f211eb716446c826ad66818ddc7810cc2cc19b3f2/cffi-2.0.0-cp313-cp313-manylinux2014_aarch64.manylinux_2_17_aarch64.whl"

[packages.wheels.hashes]
sha256 = "d48a880098c96020b02d5a1f7d9251308510ce8858940e6fa99ece33f610838b"

[[packages]]
name = "chardet"
version = "5.2.0"

[[packages.wheels]]
name = "chardet-5.2.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/38/6f/f5fbc992a329ee4e0f288c1fe0e2ad9485ed064cac731ed2fe47dcc38cbf/chardet-5.2.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "e1cf59446890a00105fe7b7912492ea04b6e6f06d4b742b2c788469e34c82970"

[[packages]]
name = "charset-normalizer"
version = "3.4.4"

[[packages.wheels]]
name = "charset_normalizer-3.4.4-cp313-cp313-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
url = "https://files.pythonhosted.org/packages/7d/62/73a6d7450829655a35bb88a88fca7d736f9882a27eacdca2c6d505b57e2e/charset_normalizer-3.4.4-cp313-cp313-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"

[packages.wheels.hashes]
sha256 = "6b39f987ae8ccdf0d2642338faf2abb1862340facc796048b604ef14919e55ed"

[[packages]]
name = "colorama"
version = "0.4.6"

[[packages.wheels]]
name = "colorama-0.4.6-py2.py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "4f1d9991f5acc0ca119f9d443620b77f9d6b33703e51011c16baf57afb285fc6"

[[packages]]
name = "coverage"
version = "7.13.0"

[[packages.wheels]]
name = "coverage-7.13.0-cp313-cp313-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
url = "https://files.pythonhosted.org/packages/df/61/b5d8105f016e1b5874af0d7c67542da780ccd4a5f2244a433d3e20ceb1ad/coverage-7.13.0-cp313-cp313-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"

[packages.wheels.hashes]
sha256 = "f4f72a85316d8e13234cafe0a9f81b40418ad7a082792fa4165bd7d45d96066b"

[[packages]]
name = "cryptography"
version = "46.0.3"

[[packages.wheels]]
name = "cryptography-46.0.3-cp311-abi3-manylinux_2_28_aarch64.whl"
url = "https://files.pythonhosted.org/packages/4b/0a/863a3604112174c8624a2ac3c038662d9e59970c7f926acdcfaed8d61142/cryptography-46.0.3-cp311-abi3-manylinux_2_28_aarch64.whl"

[packages.wheels.hashes]
sha256 = "6eae65d4c3d33da080cff9c4ab1f711b15c1d9760809dad6ea763f3812d254cb"

[[packages]]
name = "distlib"
version = "0.4.0"

[[packages.wheels]]
name = "distlib-0.4.0-py2.py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/33/6b/e0547afaf41bf2c42e52430072fa5658766e3d65bd4b03a563d1b6336f57/distlib-0.4.0-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "9659f7d87e46584a30b5780e43ac7a2143098441670ff0a49d5f9034c54a6c16"

[[packages]]
name = "filelock"
version = "3.20.1"

[[packages.wheels]]
name = "filelock-3.20.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/e3/7f/a1a97644e39e7316d850784c642093c99df1290a460df4ede27659056834/filelock-3.20.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "15d9e9a67306188a44baa72f569d2bfd803076269365fdea0934385da4dc361a"

[[packages]]
name = "idna"
version = "3.11"

[[packages.wheels]]
name = "idna-3.11-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/0e/61/66938bbb5fc52dbdf84594873d5b51fb1f7c7794e9c0f5bd885f30bc507b/idna-3.11-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "771a87f49d9defaf64091e6e6fe9c18d4833f140bd19464795bc32d966ca37ea"

[[packages]]
name = "iniconfig"
version = "2.3.0"

[[packages.wheels]]
name = "iniconfig-2.3.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/cb/b1/3846dd7f199d53cb17f49cba7e651e9ce294d8497c8c150530ed11865bb8/iniconfig-2.3.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "f631c04d2c48c52b84d0d0549c99ff3859c98df65b3101406327ecc7d53fbf12"

[[packages]]
name = "jmespath"
version = "1.0.1"

[[packages.wheels]]
name = "jmespath-1.0.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/31/b4/b9b800c45527aadd64d5b442f9b932b00648617eb5d63d2c7a6587b7cafc/jmespath-1.0.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "02e2e4cc71b5bcab88332eebf907519190dd9e6e82107fa7f83b1003a6252980"

[[packages]]
name = "msal"
version = "1.32.3"

[[packages.wheels]]
name = "msal-1.32.3-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/04/bf/81516b9aac7fd867709984d08eb4db1d2e3fe1df795c8e442cde9b568962/msal-1.32.3-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "b2798db57760b1961b142f027ffb7c8169536bf77316e99a0df5c4aaebb11569"

[[packages]]
name = "msal-extensions"
version = "1.3.1"

[[packages.wheels]]
name = "msal_extensions-1.3.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/5e/75/bd9b7bb966668920f06b200e84454c8f3566b102183bc55c5473d96cb2b9/msal_extensions-1.3.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "96d3de4d034504e969ac5e85bae8106c8373b5c6568e4c8fa7af2eca9dbe6bca"

[[packages]]
name = "packaging"
version = "25.0"

[[packages.wheels]]
name = "packaging-25.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/20/12/38679034af332785aac8774540895e234f4d07f7545804097de4b666afd8/packaging-25.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "29572ef2b1f17581046b3a2227d5c611fb25ec70ca1ba8554b24b0e69331a484"

[[packages]]
name = "pip"
version = "25.3"

[[packages.wheels]]
name = "pip-25.3-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/44/3c/d717024885424591d5376220b5e836c2d5293ce2011523c9de23ff7bf068/pip-25.3-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "9655943313a94722b7774661c21049070f6bbb0a1516bf02f7c8d5d9201514cd"

[[packages]]
name = "platformdirs"
version = "4.5.1"

[[packages.wheels]]
name = "platformdirs-4.5.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/cb/28/3bfe2fa5a7b9c46fe7e13c97bda14c895fb10fa2ebf1d0abb90e0cea7ee1/platformdirs-4.5.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "d03afa3963c806a9bed9d5125c8f4cb2fdaf74a55ab60e5d59b3fde758104d31"

[[packages]]
name = "pluggy"
version = "1.6.0"

[[packages.wheels]]
name = "pluggy-1.6.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/54/20/4d324d65cc6d9205fabedc306948156824eb9f0ee1633355a8f7ec5c66bf/pluggy-1.6.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "e920276dd6813095e9377c0bc5566d94c932c33b27a3e3945d8389c374dd4746"

[[packages]]
name = "prompt-toolkit"
version = "3.0.52"

[[packages.wheels]]
name = "prompt_toolkit-3.0.52-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/84/03/0d3ce49e2505ae70cf43bc5bb3033955d2fc9f932163e84dc0779cc47f48/prompt_toolkit-3.0.52-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "9aac639a3bbd33284347de5ad8d68ecc044b91a762dc39b7c21095fcd6a19955"

[[packages]]
name = "psutil"
version = "7.0.0"

[[packages.wheels]]
name = "psutil-7.0.0-cp36-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"
url = "https://files.pythonhosted.org/packages/eb/a2/709e0fe2f093556c17fbafda93ac032257242cabcc7ff3369e2cb76a97aa/psutil-7.0.0-cp36-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"

[packages.wheels.hashes]
sha256 = "a5f098451abc2828f7dc6b58d44b532b22f2088f4999a937557b603ce72b1993"

[[packages]]
name = "pycparser"
version = "2.23"

[[packages.wheels]]
name = "pycparser-2.23-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/a0/e3/59cd50310fc9b59512193629e1984c1f95e5c8ae6e5d8c69532ccc65a7fe/pycparser-2.23-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "e5c6e8d3fbad53479cab09ac03729e0a9faf2bee3db8208a550daf5af81a5934"

[[packages]]
name = "pygments"
version = "2.19.2"

[[packages.wheels]]
name = "pygments-2.19.2-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/c7/21/705964c7812476f378728bdf590ca4b771ec72385c533964653c68e86bdc/pygments-2.19.2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "86540386c03d588bb81d44bc3928634ff26449851e99741617ecb9037ee5ec0b"

[[packages]]
name = "pyjwt"
version = "2.10.1"

[[packages.wheels]]
name = "PyJWT-2.10.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/61/ad/689f02752eeec26aed679477e80e632ef1b682313be70793d798c1d5fc8f/PyJWT-2.10.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "dcdd193e30abefd5debf142f9adfcdd2b58004e644f25406ffaebd50bd98dacb"

[[packages]]
name = "pyproject-api"
version = "1.10.0"

[[packages.wheels]]
name = "pyproject_api-1.10.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/54/cc/cecf97be298bee2b2a37dd360618c819a2a7fd95251d8e480c1f0eb88f3b/pyproject_api-1.10.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "8757c41a79c0f4ab71b99abed52b97ecf66bd20b04fa59da43b5840bac105a09"

[[packages]]
name = "pyproject-hooks"
version = "1.2.0"

[[packages.wheels]]
name = "pyproject_hooks-1.2.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/bd/24/12818598c362d7f300f18e74db45963dbcb85150324092410c8b49405e42/pyproject_hooks-1.2.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "9e5c6bfa8dcc30091c74b0cf803c81fdd29d94f01992a7707bc97babb1141913"

[[packages]]
name = "pytest"
version = "9.0.2"

[[packages.wheels]]
name = "pytest-9.0.2-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/3b/ab/b3226f0bd7cdcf710fbede2b3548584366da3b19b5021e74f5bde2a8fa3f/pytest-9.0.2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "711ffd45bf766d5264d487b917733b453d917afd2b0ad65223959f59089f875b"

[[packages]]
name = "pytest-cov"
version = "7.0.0"

[[packages.wheels]]
name = "pytest_cov-7.0.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/ee/49/1377b49de7d0c1ce41292161ea0f721913fa8722c19fb9c1e3aa0367eecb/pytest_cov-7.0.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "3b8e9558b16cc1479da72058bdecf8073661c7f57f7d3c5f22a1c23507f2d861"

[[packages]]
name = "pyyaml"
version = "6.0.3"

[[packages.wheels]]
name = "pyyaml-6.0.3-cp313-cp313-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
url = "https://files.pythonhosted.org/packages/50/31/b20f376d3f810b9b2371e72ef5adb33879b25edb7a6d072cb7ca0c486398/pyyaml-6.0.3-cp313-cp313-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"

[packages.wheels.hashes]
sha256 = "ee2922902c45ae8ccada2c5b501ab86c36525b883eff4255313a253a3160861c"

[[packages]]
name = "questionary"
version = "2.1.1"

[[packages.wheels]]
name = "questionary-2.1.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/3c/26/1062c7ec1b053db9e499b4d2d5bc231743201b74051c973dadeac80a8f43/questionary-2.1.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "a51af13f345f1cdea62347589fbb6df3b290306ab8930713bfae4d475a7d4a59"

[[packages]]
name = "requests"
version = "2.32.5"

[[packages.wheels]]
name = "requests-2.32.5-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/1e/db/4254e3eabe8020b458f1a747140d32277ec7a271daf1d235b70dc0b4e6e3/requests-2.32.5-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "2462f94637a34fd532264295e186976db0f5d453d1cdd31473c85a6a161affb6"

[[packages]]
name = "setuptools"
version = "80.9.0"

[[packages.wheels]]
name = "setuptools-80.9.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/a3/dc/17031897dae0efacfea57dfd3a82fdd2a2aeb58e0ff71b77b87e44edc772/setuptools-80.9.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "062d34222ad13e0cc312a4c02d73f059e86a4acbfbdea8f8f76b28c99f306922"

[[packages]]
name = "tox"
version = "4.32.0"

[[packages.wheels]]
name = "tox-4.32.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/fc/cc/e09c0d663a004945f82beecd4f147053567910479314e8d01ba71e5d5dea/tox-4.32.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "451e81dc02ba8d1ed20efd52ee409641ae4b5d5830e008af10fe8823ef1bd551"

[[packages]]
name = "urllib3"
version = "2.6.2"

[[packages.wheels]]
name = "urllib3-2.6.2-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/6d/b9/4095b668ea3678bf6a0af005527f39de12fb026516fb3df17495a733b7f8/urllib3-2.6.2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "ec21cddfe7724fc7cb4ba4bea7aa8e2ef36f607a4bab81aa6ce42a13dc3f03dd"

[[packages]]
name = "vcrpy"
version = "8.1.0"

[[packages.wheels]]
name = "vcrpy-8.1.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/09/77/892bcd82445ac949816205b51ab80deb86a492a315f2e290ed4eab35021c/vcrpy-8.1.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "fc4fb6e954c6d082ba6d329c6f3d1228f5b1b1d2836f9022c301b587cfad7378"

[[packages]]
name = "virtualenv"
version = "20.35.4"

[[packages.wheels]]
name = "virtualenv-20.35.4-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/79/0c/c05523fa3181fdf0c9c52a6ba91a23fbf3246cc095f26f6516f9c60e6771/virtualenv-20.35.4-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "c21c9cede36c9753eeade68ba7d523529f228a403463376cf821eaae2b650f1b"

[[packages]]
name = "wcwidth"
version = "0.2.14"

[[packages.wheels]]
name = "wcwidth-0.2.14-py2.py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/af/b5/123f13c975e9f27ab9c0770f514345bd406d0e8d3b7a0723af9d43f710af/wcwidth-0.2.14-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "a7bb560c8aee30f9957e5f9895805edd20602f2d7f720186dfd906e82b4982e1"

[[packages]]
name = "wrapt"
version = "2.0.1"

[[packages.wheels]]
name = "wrapt-2.0.1-cp313-cp313-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"
url = "https://files.pythonhosted.org/packages/0f/6b/806dbf6dd9579556aab22fc92908a876636e250f063f71548a8660382184/wrapt-2.0.1-cp313-cp313-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl"

[packages.wheels.hashes]
sha256 = "c654eafb01afac55246053d67a4b9a984a3567c3808bb7df2f8de1c1caba2e1c"
